name: Triggered workflow turn style
on:
  repository_dispatch:
    types: [triggered]
jobs:
  run:
    name: Build website
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.client_payload.ref }}
          
      - name: Turnstyle
        uses: softprops/turnstyle@v1
  
      - name: print payload sha
        run: 'echo "field: ${{ github.event.client_payload.sha }}, ${{ github.event.client_payload.ref }}, ${{ github.event.client_payload.repo }}"'
      
#       - name: action turnstyle
#         uses: softprops/turnstyle@v0.1.2

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Restore yarn cache
        uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
            ${{ runner.os }}-yarn-

      - name: Install deps
        run: yarn
      
      - name: Restore zh-docs-dm-cache
        uses: actions/cache@v2
        id: zh-docs-dm-cache
        with: 
          path: ./markdown-pages/contents/zh/docs-dm
          key: ${{ runner.os }}-zh-docs-dm-cache-build-${{ github.event.client_payload.sha }}
          restore-keys: | 
            ${{ runner.os }}-zh-docs-dm-cache-build-${{ github.event.client_payload.sha }}
            ${{ runner.os }}-zh-docs-dm-cache-build-
            ${{ runner.os }}-zh
      
      - name: Split ref
        id: git-ref
        run: echo "::set-output name=ref::$(echo ${{github.event.client_payload.ref##*/}})"
      
      - name: Get ref
        run: 'echo "ref: ${{ steps.git-ref.outputs.ref }}"'

      - name: Sync zh-docs-dm
        run: GITHUB_AUTHORIZATION_TOKEN=${{ secrets.GH_TOKEN }} yarn sync docs-dm ${{ steps.git-ref.outputs.ref }} ${{ github.event.client_payload.sha }}
      
      - name: Restore en-docs-dm-cache
        uses: actions/cache@v2
        id: en-docs-dm-cache
        with: 
          path: ./markdown-pages/contents/en/docs-dm
          key: ${{ runner.os }}-en-docs-dm-cache-build-${{ github.event.client_payload.sha }}
          restore-keys: | 
            ${{ runner.os }}-en-docs-dm-cache-build-${{ github.event.client_payload.sha }}
            ${{ runner.os }}-en-docs-dm-cache-build-
            ${{ runner.os }}-en

      - name: Download all en-docs-dm
        if: steps.en-docs-dm-cache.outputs.cache-hit != 'true'
        run: GITHUB_AUTHORIZATION_TOKEN=${{ secrets.GH_TOKEN }} yarn download:docs-dm:en:all

      - name: Restore gatsby cache
        uses: actions/cache@v2
        id: gatsby-cache
        with:
          path: ./.cache
          key: ${{ runner.os }}-gatsby-cache2-${{ github.event.client_payload.sha }}
          restore-keys: |
            ${{ runner.os }}-gatsby-cache2-${{ github.event.client_payload.sha }}
            ${{ runner.os }}-gatsby-cache2-

      - name: Restore gatsby build
        uses: actions/cache@v2
        id: gatsby-build
        with:
          path: ./public
          key: ${{ runner.os }}-gatsby-build2-${{ github.event.client_payload.sha }}
          restore-keys: |
            ${{ runner.os }}-gatsby-build2-${{ github.event.client_payload.sha }}
            ${{ runner.os }}-gatsby-build2-

      - name: Build website
        run: GATSBY_EXPERIMENTAL_PAGE_BUILD_ON_DATA_CHANGES=true GATSBY_ALGOLIA_APPLICATION_ID=${{ secrets.ALGOLIA_APPLICATION_ID }} GATSBY_ALGOLIA_API_KEY=${{ secrets.ALGOLIA_API_KEY }} yarn build --write-to-file

      - name: Move changed files from gatsby
        run: (yes|cp -f .cache/*Pages.txt public)|true

      - name: List public
        run: ls ./public

#       - name: cat new page
#         run : cat ./public/newPages.txt
      
#       - name: cat deleted page
#         run : cat ./public/deletedPages.txt

      # - name: Deploy
      #   run: |
      #     rsync -avz --delete public/ "${{ secrets.SSH_USER }}@${{ secrets.BJ_1_HOST }}:${{ secrets.DEPLOY_PATH }}"
      #     rsync -avz --delete public/ "${{ secrets.SSH_USER }}@${{ secrets.BJ_2_HOST }}:${{ secrets.DEPLOY_PATH }}"
      #     rsync -avz --delete public/ "${{ secrets.SSH_USER }}@${{ secrets.LA_1_HOST }}:${{ secrets.DEPLOY_PATH }}"
      #     rsync -avz --delete public/ "${{ secrets.SSH_USER }}@${{ secrets.LA_2_HOST }}:${{ secrets.DEPLOY_PATH }}"
