name: Test serilize workflow
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  repository_dispatch:
    types: [triggered]
jobs:
  run:
    name: Build website
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.client_payload.ref }}
  
      - name: print payload sha
        run: 'echo "field: ${{ github.event.client_payload.sha }}"'
      
      - name: action turnstyle
        uses: softprops/turnstyle@v0.1.2

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Restore yarn cache
        uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
            ${{ runner.os }}-yarn-

      - name: Install deps
        run: yarn

      - name: Download docs-dm
        run: GITHUB_AUTHORIZATION_TOKEN=${{ secrets.GH_TOKEN }} yarn download:docs-dm:all
      
      - name: Get webhook payload sha
        if: ${{ github.event.client_payload.sha }}
        run: echo "::set-output name=sha::$(${{ github.event.client_payload.sha }})"
      
      - name: Get sha
        if: ${{ github.event.client_payload.sha }} == ''
        run: echo "::set-output name=sha::$(${{ github.sha }})"
      
      - name: print sha
        run: 'echo "sha: ${{ steps.get-sha.outputs.sha }}"'
      
      - name: Restore gatsby cache
        uses: actions/cache@v2
        id: payload-gatsby-cache
        with:
          path: ./.cache
          key: ${{ runner.os }}-gatsby-cache-${{ steps.get-sha.outputs.sha }}
          restore-keys: |
            ${{ runner.os }}-gatsby-cache-${{ steps.get-sha.outputs.sha }}
            ${{ runner.os }}-gatsby-cache-

      - name: Restore gatsby build
        uses: actions/cache@v2
        id: gatsby-build
        with:
          path: ./public
          key: ${{ runner.os }}-gatsby-build-${{ steps.get-sha.outputs.sha }}
          restore-keys: |
            ${{ runner.os }}-gatsby-build-${{ steps.get-sha.outputs.sha }}
            ${{ runner.os }}-gatsby-build-

      - name: Build website
        run: GATSBY_EXPERIMENTAL_PAGE_BUILD_ON_DATA_CHANGES=true GATSBY_ALGOLIA_APPLICATION_ID=${{ secrets.ALGOLIA_APPLICATION_ID }} GATSBY_ALGOLIA_API_KEY=${{ secrets.ALGOLIA_API_KEY }} yarn build --write-to-file

      - name: Move changed files from gatsby
        run: (yes|cp -f .cache/*Pages.txt public)|true

      - name: List public
        run: ls ./public

#       - name: cat new page
#         run : cat ./public/newPages.txt
      
#       - name: cat deleted page
#         run : cat ./public/deletedPages.txt

      # - name: Deploy
      #   run: |
      #     rsync -avz --delete public/ "${{ secrets.SSH_USER }}@${{ secrets.BJ_1_HOST }}:${{ secrets.DEPLOY_PATH }}"
      #     rsync -avz --delete public/ "${{ secrets.SSH_USER }}@${{ secrets.BJ_2_HOST }}:${{ secrets.DEPLOY_PATH }}"
      #     rsync -avz --delete public/ "${{ secrets.SSH_USER }}@${{ secrets.LA_1_HOST }}:${{ secrets.DEPLOY_PATH }}"
      #     rsync -avz --delete public/ "${{ secrets.SSH_USER }}@${{ secrets.LA_2_HOST }}:${{ secrets.DEPLOY_PATH }}"
